spring.application.name=Projekt2_Gruppe_5

# Database connection - bruger miljøvariabler på Azure, ellers localhost
spring.datasource.url=${JDBC_DATABASE_URL:jdbc:mysql://localhost:3306}
spring.datasource.username=${JDBC_USERNAME:root}
spring.datasource.password=${JDBC_PASSWORD:1234}

# Driver class
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Kør schema.sql og data.sql ved opstart
spring.sql.init.mode=always

# Slå Thymeleaf cache fra under udvikling
spring.thymeleaf.cache=false