spring.application.name=Projekt2_Gruppe_5

# Database connection - bruger miljøvariabler på Azure, ellers localhost
# spring.datasource.url=${JDBC_DATABASE_URL:jdbc:mysql://localhost:3306}
spring.datasource.url=${JDBC_DATABASE_URL:jdbc:mysql://20.199.138.56:3306/wishlist_db}
spring.datasource.username=${JDBC_USERNAME:root}
#spring.datasource.password=${JDBC_PASSWORD:1234}
spring.datasource.password=${JDBC_PASSWORD:mypassword}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

spring.thymeleaf.cache=false